# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5365e90b8f7f0fc34f845eb2d720fd1dbfeef7a589cf2aa244ef352a6f75cb65d8ca822250fc68b1976800f37f5465d1b2d887cb6ec5ead3c34b7c6bbb856446

test:
  secret_key_base: 859adc8bf94430c52f535981811efb2c8bed8eab8ce75b002c3d5d01f899082a0f882809c9fb64155555a48a5e68b4aab3f333282163b774481cf7cbacd2c004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
